services:
  qwen2_5-vl:
    image: lianshufeng/model_api:qwen2_5vl
#    shm_size: 6.15g
    ports:
      - "8080:8080"
    privileged: true
    container_name: qwen2_5vl
    restart: always
    environment:
      - CUDA_VISIBLE_DEVICES=0 # 多卡 0,1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: "all"
              capabilities: [gpu]
    volumes:
        - E:/git/huggingface/Qwen/Qwen2.5-VL-3B-Instruct:/models
    command: python Qwen2_5VLMain.py --model=/models
    # command: sleep 1000
